# Configuración de build para el proyecto
[build]
  # El frontend no necesita un paso de build, se publica desde la raíz
  publish = "."
  
# Configuración explícita para las funciones serverless
[functions]
  # Directorio donde se encuentran las funciones
  directory = "api/"
  # Especifica que las dependencias de las funciones están en el `package.json` principal
  # y deben ser instaladas y empaquetadas.
  external_node_modules = ["@google/generative-ai", "formidable", "pdf-parse"]
  node_bundler = "esbuild"